on:
  push:
    tags:
      - 'v*.*.*'   # trigger on semver-style tags like v1.2.0

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node (optional)
        # if you need node for packaging scripts; otherwise remove
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create add-on zip
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ADDON_DIR="bluetooth-manager"
          ZIP_NAME="${ADDON_DIR}-${VERSION}.zip"
          cd "$GITHUB_WORKSPACE"
          if [ ! -d "$ADDON_DIR" ]; then
            echo "Add-on directory $ADDON_DIR not found" >&2
            exit 1
          fi
          # remove dev artifacts and create zip
          zip -r "$ZIP_NAME" "$ADDON_DIR" -x "**/.git/**" "**/node_modules/**"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "bluetooth-manager ${{ github.ref_name }}"
          body: |
            See CHANGELOG.md for full details.
            Short release notes or highlights here.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bluetooth-manager-${{ github.ref_name }}.zip
          asset_name: bluetooth-manager-${{ github.ref_name }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
